Update ProtobufJsonPayloadConverter.java
temporalio/sdk-java pull request #552
Opened 2021-06-23 10:41 UTC by mschielmann

Regarding #551 - bugfix - use preconfigured printer rather than default JsonFormat.printer();

## What was changed
Bugfix - In JavaSDK, ProtobufJsonPayloadConverter allows you to configure both printer and parser. Yet, the preconfigured printer has not been used to convert Object to data. Default JsonFormat printer has been used instead.

## Why?
Bugfix to allow configurable printer to be used (as designed, it can be passed as constructor param).

## Checklist
1. Closes #551

2. How was this tested:
Passed custom JsonFormat.Printer to constructor and see it being used.

2021-06-23 10:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/temporalio/sdk-java?pullRequest=552) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/temporalio/sdk-java?pullRequest=552) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/temporalio/sdk-java?pullRequest=552) it.</sub>

2021-07-02 18:21 UTC, Spikhalskiy requested changes
While this change is totally reasonable and compatible, it looks like it will change the way we serialize photo field names. We use `JsonFormat.printer()` now and we will use `JsonFormat.printer().preservingProtoFieldNames()` if this PR applied as it is. Could you please edit the constructor to preserve the current behavior?

2021-07-02 18:57 UTC, mschielmann commented
hi @Spikhalskiy thank you for your review - good catch, I've made a change you've requested (I hope that's what you've meant).

2021-07-02 19:03 UTC, Spikhalskiy approved these changes

2021-07-02 19:07 UTC, merged